# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af57e70189afca530bafeff283b58fc7d3075d04cafd4ff09627c2a6c98bf1e94dac302b8e5d858f32682ec5aa9b6879a6d99418db72b8eed187c8e2667aac8

test:
  secret_key_base: d1bda6e7f4eae4b0918ff6cdcba9db6ffea3e73cadfa6b776e9b06613d3b8a72005d82a1f16a77864bb68f8e27a5fbfa3a94698098b5203a449192640ecd1a84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
